ignoreLogs = ['warning-goldmark-raw-html']

#On 2024-03-12
#Updated build timeout to 60s instead of the default 30s
#Netlify build reached just > 30s
timeout = "60s"

# Change baseurl before deploy
baseurl = "https://jeremielitzLer.fr"
languageCode = "fr-fr"

title = "Jérémie Litzler"
description = "Je partage ici mes notes et experiences qui, je suis sûr, seront utiles pour au moins une personne. Bonne lecture !"

[pagination]
pagerSize = 8

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "fr"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
# disqusShortname = "hugo-theme-stack"

# See https://gohugo.io/getting-started/configuration/#removepathaccents
removePathAccents = true

[params]
custom_css = ["css/custom-style.css"]