[[redirects]]
from = "/2021/08/quel-chocolat-100-pour-100/"
to = "/post/2021-08/quel-chocolat-100-pour-100"
status = 301
force = true

[[redirects]]
from = "/2021/08/reduire-son-exposition-a-la-lumiere-bleue/"
to = "/post/2021-08/reduire-son-exposition-a-la-lumiere-bleue"
status = 301
force = true

[[redirects]]
from = "/2022/05/les-bases-d-une-installation-solaire-en-autonomie-larchipelle/"
to = "/post/2022-05/les-bases-d-une-installation-solaire-en-autonomie-larchipelle"
status = 301
force = true

[[redirects]]
from = "/2022/06/retour-d-experience-sur-une-installation-pv-1mois/"
to = "/post/2022-06/retour-d-experience-sur-une-installation-pv-1mois"
status = 301
force = true

[[redirects]]
from = "/2022/07/5-sauvages-1-damien-dekarz/"
to = "/post/2022-07/5-sauvages-1-damien-dekarz"
status = 301
force = true

[[redirects]]
from = "/2022/10/10-legumes-a-planter-en-octobre-le-potager-d-olivier/"
to = "/post/2022-10/10-legumes-a-planter-en-octobre-le-potager-d-olivier"
status = 301
force = true

[[redirects]]
from = "/2022/10/comment-jardiner-avec-un-sol-vivant-damien-dekarz/"
to = "/post/2022-10/comment-jardiner-avec-un-sol-vivant-damien-dekarz"
status = 301
force = true

[[redirects]]
from = "/2022/10/que-faire-au-jardin-en-octobre-damien-dekarz/"
to = "/post/2022-10/que-faire-au-jardin-en-octobre-damien-dekarz"
status = 301
force = true

[[redirects]]
from = "/2022/11/optimiser-l-autonomie-electrique/"
to = "/post/2022-11/optimiser-l-autonomie-electrique"
status = 301
force = true

[[redirects]]
from = "/2022/11/vos-bougies-en-cire-dabeille-et-rouleaux-de-papier-wc/"
to = "/post/2022-11/vos-bougies-en-cire-dabeille-et-rouleaux-de-papier-wc"
status = 301
force = true

[[redirects]]
from = "/2022/12/retour-d-experience-sur-une-installation-pv-9mois-partie-1/"
to = "/post/2022-12/retour-d-experience-sur-une-installation-pv-9mois-partie-1"
status = 301
force = true

[[redirects]]
from = "/2022/12/retour-d-experience-sur-une-installation-pv-9mois-partie-2/"
to = "/post/2022-12/retour-d-experience-sur-une-installation-pv-9mois-partie-2"
status = 301
force = true

[[redirects]]
from = "/2023/01/3-trucs-a-faire-en-janvier-au-jardin-damien-dekarz/"
to = "/post/2023-01/3-trucs-a-faire-en-janvier-au-jardin-damien-dekarz"
status = 301
force = true

[[redirects]]
from = "/2023/01/calculer-le-retour-sur-investissement-pv/"
to = "/post/2023-01/calculer-le-retour-sur-investissement-pv"
status = 301
force = true

[[redirects]]
from = "/2023/01/eglantier-immunite-circulation-et-articulations-altheaprocence/"
to = "/post/2023-01/eglantier-immunite-circulation-et-articulations-altheaprocence"
status = 301
force = true

[[redirects]]
from = "/2023/01/en-janvier-pas-de-semis-ou-presque-le-potager-dolivier/"
to = "/post/2023-01/en-janvier-pas-de-semis-ou-presque-le-potager-dolivier"
status = 301
force = true

[[redirects]]
from = "/2023/01/le-roncier-rubus-fruticosus-le-chemin-de-la-nature/"
to = "/post/2023-01/le-roncier-rubus-fruticosus-le-chemin-de-la-nature"
status = 301
force = true

[[redirects]]
from = "/2023/01/le-rosier-sauvage-bourgeons-et-cynorhodons-le-chemin-de-la-nature/"
to = "/post/2023-01/le-rosier-sauvage-bourgeons-et-cynorhodons-le-chemin-de-la-nature"
status = 301
force = true

[[redirects]]
from = "/2023/01/prele-des-champs-equisetum-arvense-altheaprocence/"
to = "/post/2023-01/prele-des-champs-equisetum-arvense-altheaprocence"
status = 301
force = true

[[redirects]]
from = "/2023/01/que-faire-au-jardin-en-janvier-damien-dekarz/"
to = "/post/2023-01/que-faire-au-jardin-en-janvier-damien-dekarz"
status = 301
force = true

[[redirects]]
from = "/2023/01/ronce-murier-mure-bienfaits-et-usages-altheaprocence/"
to = "/post/2023-01/ronce-murier-mure-bienfaits-et-usages-altheaprocence"
status = 301
force = true

[[redirects]]
from = "/2023/02/3-trucs-a-faire-en-fevrier-au-jardin-damien-dekarz/"
to = "/post/2023-02/3-trucs-a-faire-en-fevrier-au-jardin-damien-dekarz"
status = 301
force = true

[[redirects]]
from = "/2023/02/jardiner-avec-les-preles-damien-dekarz/"
to = "/post/2023-02/jardiner-avec-les-preles-damien-dekarz"
status = 301
force = true

[[redirects]]
from = "/2023/02/la-vigne-de-a-a-z-presque-damien-dekarz/"
to = "/post/2023-02/la-vigne-de-a-a-z-presque-damien-dekarz"
status = 301
force = true

[[redirects]]
from = "/2023/02/les-bienfaits-de-lortie-altheaprocence/"
to = "/post/2023-02/les-bienfaits-de-lortie-altheaprocence"
status = 301
force = true

[[redirects]]
from = "/2023/02/les-vertus-de-la-prele-des-champs-le-chemin-de-la-nature/"
to = "/post/2023-02/les-vertus-de-la-prele-des-champs-le-chemin-de-la-nature"
status = 301
force = true

[[redirects]]
from = "/2023/02/lortie-brulante-le-chemin-de-la-nature/"
to = "/post/2023-02/lortie-brulante-le-chemin-de-la-nature"
status = 301
force = true

[[redirects]]
from = "/2023/02/lortie-tous-ses-secrets-le-chemin-de-la-nature/"
to = "/post/2023-02/lortie-tous-ses-secrets-le-chemin-de-la-nature"
status = 301
force = true

[[redirects]]
from = "/2023/02/recette-aux-orties-et-au-lierre-terrestre-le-chemin-de-la-nature/"
to = "/post/2023-02/recette-aux-orties-et-au-lierre-terrestre-le-chemin-de-la-nature"
status = 301
force = true

[[redirects]]
from = "/2023/03/3-trucs-a-faire-en-mars-au-jardin-damien-dekarz/"
to = "/post/2023-03/3-trucs-a-faire-en-mars-au-jardin-damien-dekarz"
status = 301
force = true

[[redirects]]
from = "/2023/03/comment-j-organise-mon-activite-digitale/"
to = "/post/2023-03/comment-j-organise-mon-activite-digitale"
status = 301
force = true

[[redirects]]
from = "/2023/03/galette-de-sarrasin-ecolo-au-pesto-dortie-noix-lenergie-autrement/"
to = "/post/2023-03/galette-de-sarrasin-ecolo-au-pesto-dortie-noix-lenergie-autrement"
status = 301
force = true

[[redirects]]
from = "/2023/03/interview-de-raymonde-gal-sur-lortie-larchipelle/"
to = "/post/2023-03/interview-de-raymonde-gal-sur-lortie-larchipelle"
status = 301
force = true

[[redirects]]
from = "/2023/03/la-guerre-de-lortie-avec-bernard-bertrand-damien-dekarz/"
to = "/post/2023-03/la-guerre-de-lortie-avec-bernard-bertrand-damien-dekarz"
status = 301
force = true

[[redirects]]
from = "/2023/03/les-plantes-sauvages-a-la-sortie-de-lhiver-larchipelle/"
to = "/post/2023-03/les-plantes-sauvages-a-la-sortie-de-lhiver-larchipelle"
status = 301
force = true

[[redirects]]
from = "/2023/03/ortie-piqure-et-cookies-damien-dekarz/"
to = "/post/2023-03/ortie-piqure-et-cookies-damien-dekarz"
status = 301
force = true

[[redirects]]
from = "/2023/03/retour-d-experience-sur-une-installation-pv-1an/"
to = "/post/2023-03/retour-d-experience-sur-une-installation-pv-1an"
status = 301
force = true

[[redirects]]
from = "/2023/04/3-trucs-a-faire-en-avril-au-jardin-damien-dekarz/"
to = "/post/2023-04/3-trucs-a-faire-en-avril-au-jardin-damien-dekarz"
status = 301
force = true

[[redirects]]
from = "/2023/04/la-consoude-altheaprocence/"
to = "/post/2023-04/la-consoude-altheaprocence"
status = 301
force = true

[[redirects]]
from = "/2023/04/tout-sur-la-grande-consoude-le-chemin-de-la-nature/"
to = "/post/2023-04/tout-sur-la-grande-consoude-le-chemin-de-la-nature"
status = 301
force = true

[[redirects]]
from = "/2023/05/3-trucs-a-faire-en-mai-au-jardin-damien-dekarz/"
to = "/post/2023-05/3-trucs-a-faire-en-mai-au-jardin-damien-dekarz"
status = 301
force = true

[[redirects]]
from = "/2023/05/activer-netlifycms-sur-son-site-web/"
to = "/post/2023-05/activer-netlifycms-sur-son-site-web"
status = 301
force = true

[[redirects]]
from = "/2023/05/comment-realiser-son-site-moderne-et-rapide/"
to = "/post/2023-05/comment-realiser-son-site-moderne-et-rapide"
status = 301
force = true

[[redirects]]
from = "/2023/05/creer-son-site-moderne-rapide/"
to = "/post/2023-05/creer-son-site-moderne-rapide"
status = 301
force = true

[[redirects]]
from = "/2023/05/deployer-son-site-moderne-rapide/"
to = "/post/2023-05/deployer-son-site-moderne-rapide"
status = 301
force = true

[[redirects]]
from = "/2023/05/le-pissenlit-altheaprocence/"
to = "/post/2023-05/le-pissenlit-altheaprocence"
status = 301
force = true

[[redirects]]
from = "/2023/05/le-pissenlit-est-notre-ami-le-chemin-de-la-nature/"
to = "/post/2023-05/le-pissenlit-est-notre-ami-le-chemin-de-la-nature"
status = 301
force = true

[[redirects]]
from = "/2023/05/preparer-un-env-pour-un-site-moderne-rapide/"
to = "/post/2023-05/preparer-un-env-pour-un-site-moderne-rapide"
status = 301
force = true

[[redirects]]
from = "/2023/06/3-trucs-a-faire-en-juin-au-jardin-damien-dekarz/"
to = "/post/2023-06/3-trucs-a-faire-en-juin-au-jardin-damien-dekarz"
status = 301
force = true

[[redirects]]
from = "/2023/06/configurer-substack-avec-plusieurs-langues-en-2023/"
to = "/post/2023-06/configurer-substack-avec-plusieurs-langues-en-2023"
status = 301
force = true

[[redirects]]
from = "/2023/06/le-gingembre-altheaprocence/"
to = "/post/2023-06/le-gingembre-altheaprocence"
status = 301
force = true

[[redirects]]
from = "/2023/06/mon-potager-en-juin-visite-damien-dekarz/"
to = "/post/2023-06/mon-potager-en-juin-visite-damien-dekarz"
status = 301
force = true

[[redirects]]
from = "/2023/06/que-faire-au-jardin-en-juin-damien-dekarz/"
to = "/post/2023-06/que-faire-au-jardin-en-juin-damien-dekarz"
status = 301
force = true

[[redirects]]
from = "/2023/06/recevoir-un-seul-bulletin-d-information-sur-ma-publication/"
to = "/post/2023-06/recevoir-un-seul-bulletin-d-information-sur-ma-publication"
status = 301
force = true

[[redirects]]
from = "/2023/07/3-trucs-a-faire-en-juillet-au-jardin-damien-dekarz/"
to = "/post/2023-07/3-trucs-a-faire-en-juillet-au-jardin-damien-dekarz"
status = 301
force = true

[[redirects]]
from = "/2023/07/5-plantes-sauvages-au-jardin-juillet-et-juin-david-bricout/"
to = "/post/2023-07/5-plantes-sauvages-au-jardin-juillet-et-juin-david-bricout"
status = 301
force = true

[[redirects]]
from = "/2023/07/retour-experience-e-bike-bafang/"
to = "/post/2023-07/retour-experience-e-bike-bafang"
status = 301
force = true

[[redirects]]
from = "/2023/08/3-trucs-a-faire-en-aout-au-jardin/"
to = "/post/2023-08/3-trucs-a-faire-en-aout-au-jardin"
status = 301
force = true

[[redirects]]
from = "/2023/08/maison-semi-enterree-en-autonomie/"
to = "/post/2023-08/maison-semi-enterree-en-autonomie"
status = 301
force = true


#[[headers]]
#for = "/*"
#[headers.values]
#Content-Security-Policy = "default-src 'self';"

# Thanks to https://answers.netlify.com/t/support-guide-how-to-use-the-ignore-command/37517
[build]
ignore = "exit 1"
